/**
 * Keyvalues (VDF) text read in order, with where each entry is in the text.
 *
 * A JS object can't hold a BEE2 file exactly: it groups a repeated key into
 * an array, and puts keys that are numbers (like MapInstVar's value mappings)
 * before the rest. Entries read here keep their order and their place in the
 * text, so parts of a file can be written back exactly as they were.
 */
const vdf = require("vdf-parser")

const APP_VERSION = require("../../package.json").version

/** The first line of the files BeePEE writes: BeePEE, and its version */
const GENERATED_HEADER = `//Generated by BeePEE v${APP_VERSION} (@https://github.com/BeemodTools/BeePEE )`

/**
 * The version of BeePEE that wrote a file, from its first line
 * (GENERATED_HEADER): "" when BeePEE wrote it before that had the version,
 * null when BeePEE didn't write it
 */
function beepeeVersionOf(text) {
    let start = String(text ?? "")
    // After a byte order mark
    if (start.charCodeAt(0) === 0xfeff) start = start.slice(1)
    const firstLine = start.match(/^[^\r\n]*/)[0]
    const header = firstLine.match(/^\s*\/\/\s*Generated by BeePEE(?:\s+v(\S+))?/i)
    if (!header) return null
    return header[1] ?? ""
}

/** An error at a place in the text, with its line number */
function textError(text, at, message) {
    const line = text.slice(0, at).split("\n").length
    return new Error(`line ${line}: ${message}`)
}

/** Quoted and bare strings, braces and [flags], with where each is */
function tokenize(text) {
    const tokens = []
    let i = 0
    while (i < text.length) {
        const c = text[i]
        if (/\s/.test(c)) {
            i++
        } else if (c === "/" && text[i + 1] === "/") {
            while (i < text.length && text[i] !== "\n") i++
        } else if (c === "{" || c === "}") {
            tokens.push({ type: c, start: i, end: i + 1 })
            i++
        } else if (c === "[") {
            const close = text.indexOf("]", i)
            const lineEnd = text.indexOf("\n", i)
            if (close === -1 || (lineEnd !== -1 && lineEnd < close)) {
                throw textError(text, i, "a [flag] has no ]")
            }
            tokens.push({ type: "flag", start: i, end: close + 1 })
            i = close + 1
        } else if (c === '"') {
            let j = i + 1
            while (j < text.length && text[j] !== '"') {
                j += text[j] === "\\" ? 2 : 1
            }
            if (j >= text.length) {
                throw textError(text, i, "a quoted string has no closing quote")
            }
            tokens.push({
                type: "string",
                value: text.slice(i + 1, j),
                start: i,
                end: j + 1,
            })
            i = j + 1
        } else {
            let j = i
            while (j < text.length && !/[\s{}"]/.test(text[j])) j++
            tokens.push({
                type: "string",
                value: text.slice(i, j),
                start: i,
                end: j,
            })
            i = j
        }
    }
    return tokens
}

/**
 * The entries of keyvalues text, in order. Each is { key, value } or
 * { key, children, open, close } (where its braces are), with start and end:
 * where it is in the text, from its key to its value or closing brace and
 * any [flags] after them.
 */
function parse(text) {
    const tokens = tokenize(text)
    let next = 0

    const readBlock = (open) => {
        const entries = []
        for (;;) {
            const token = tokens[next]
            if (!token) {
                if (open) throw textError(text, open.start, "a { has no }")
                return { entries, close: null }
            }
            next++
            if (token.type === "}") {
                if (!open) throw textError(text, token.start, "a } has no {")
                return { entries, close: token }
            }
            if (token.type === "{") {
                throw textError(text, token.start, "a { has no name before it")
            }
            if (token.type === "flag") {
                // A flag after a value or block is part of that entry
                const last = entries[entries.length - 1]
                if (!last) {
                    throw textError(
                        text,
                        token.start,
                        "a [flag] has nothing before it",
                    )
                }
                last.end = token.end
                continue
            }

            const entry = { key: token.value, start: token.start }
            let value = tokens[next]
            // A flag between a block's name and its { (or after a key)
            while (value && value.type === "flag") value = tokens[++next]
            if (!value || value.type === "}") {
                throw textError(
                    text,
                    token.start,
                    `"${token.value}" has no value`,
                )
            }
            next++
            if (value.type === "{") {
                const block = readBlock(value)
                entry.children = block.entries
                entry.open = value.start
                entry.close = block.close.start
                entry.end = block.close.end
            } else {
                entry.value = value.value
                entry.end = value.end
            }
            entries.push(entry)
        }
    }

    return readBlock(null).entries
}

/**
 * Whether two lists of entries say the same: the same keys (in any case, as
 * BEE2 reads them) and values, in the same order
 */
function sameEntries(a, b) {
    if (a.length !== b.length) return false
    return a.every((entry, i) => {
        const other = b[i]
        if (entry.key.toLowerCase() !== other.key.toLowerCase()) return false
        if (entry.children || other.children) {
            return Boolean(entry.children && other.children) &&
                sameEntries(entry.children, other.children)
        }
        return entry.value === other.value
    })
}

/**
 * Keyvalues text as a JS object, the way BeePEE has always read VDF files: a
 * repeated key's values in an array, an empty key as "desc_N", and a
 * condition flag in its key ("Tooltip [lang_zh]", which convertJsonToVdf in
 * packageManager puts back after the value)
 */
function toObject(text) {
    let emptyKeyCounter = 0
    const lines = text.split("\n").map((line) =>
        line
            // Windows line ends aren't needed (and "." doesn't match them,
            // below)
            .replace(/\r$/, "")
            .replace(/^(\s*)""\s+(".*")/, (match, indent, value) => {
                return `${indent}"desc_${emptyKeyCounter++}" ${value}`
            })
            // A condition flag after a value or a block's name
            // ("Tooltip" "..." [lang_zh]), which the parser can't read, goes
            // into the key ("Tooltip [lang_zh]")
            .replace(
                /^(\s*)"([^"\n]*)"(\s+"(?:[^"\\\n]|\\.)*")?\s*(\[[^\]\n]+\])\s*(?:\/\/.*)?$/,
                (match, indent, key, value = "", flag) =>
                    `${indent}"${key} ${flag}"${value}`,
            ),
    )
    return vdf.parse(lines.join("\n"))
}

/** VDF tokens can't hold raw newlines or quotes (BEE2 reads no escapes) */
function vdfToken(value) {
    return String(value).replace(/\r?\n/g, " ").replace(/"/g, "'")
}

/**
 * A JS object as keyvalues text, each line indented by `depth` tabs and ended
 * with `eol`. An array is a key repeated for each of its values.
 */
function stringify(object, depth = 0, eol = "\n") {
    const indent = "\t".repeat(depth)
    let text = ""
    for (const [key, value] of Object.entries(object)) {
        for (const each of Array.isArray(value) ? value : [value]) {
            if (each && typeof each === "object") {
                text += `${indent}"${vdfToken(key)}"${eol}${indent}{${eol}`
                text += stringify(each, depth + 1, eol)
                text += `${indent}}${eol}`
            } else {
                const value = vdfToken(each ?? "")
                text += `${indent}"${vdfToken(key)}" "${value}"${eol}`
            }
        }
    }
    return text
}

module.exports = {
    APP_VERSION,
    GENERATED_HEADER,
    beepeeVersionOf,
    parse,
    sameEntries,
    toObject,
    stringify,
    vdfToken,
}
