jest.mock("electron", () => ({
    app: { isPackaged: false, getPath: () => require("os").tmpdir() },
    dialog: {},
    ipcMain: { handle() {}, on() {} },
    BrowserWindow: { getAllWindows: () => [] },
}))

const fs = require("fs")
const os = require("os")
const path = require("path")
const {
    APP_VERSION,
    GENERATED_HEADER,
    beepeeVersionOf,
} = require("../utils/keyvalues")

describe("the BeePEE version a file's first line gives", () => {
    test("is the version that wrote it", () => {
        expect(beepeeVersionOf(`${GENERATED_HEADER}\n"Item"\n{\n}\n`)).toBe(
            APP_VERSION,
        )
        // After a byte order mark, with Windows line ends
        expect(
            beepeeVersionOf(
                `${String.fromCharCode(0xfeff)}//Generated by BeePEE v1.2.0-beta.1 (@https://github.com/BeemodTools/BeePEE )\r\n"Item"`,
            ),
        ).toBe("1.2.0-beta.1")
    })

    test("is blank for one BeePEE wrote before it had the version", () => {
        expect(
            beepeeVersionOf(
                '//Generated by BeePEE (@https://github.com/Areng14/BeePEE )\n"Item"',
            ),
        ).toBe("")
    })

    test("is null for a file BeePEE didn't write", () => {
        expect(beepeeVersionOf('"Item"\n{\n}\n')).toBeNull()
        expect(beepeeVersionOf("// My item\n")).toBeNull()
        expect(beepeeVersionOf('"Item" // Generated by BeePEE v1.0.0')).toBeNull()
    })
})

describe("whether BeePEE made an item", () => {
    let dir

    beforeEach(() => {
        dir = fs.mkdtempSync(path.join(os.tmpdir(), "beepee-made-with-"))
    })

    afterEach(() => {
        fs.rmSync(dir, { recursive: true, force: true })
    })

    const itemDir = (folder) => path.join(dir, "items", folder)
    const metaOf = (folder) =>
        JSON.parse(fs.readFileSync(path.join(itemDir(folder), "meta.json"), "utf8"))

    /** An imported item: its editoritems.txt (after firstLine), and a meta.json if it came with one */
    function importedItem(folder, firstLine, meta) {
        fs.mkdirSync(itemDir(folder), { recursive: true })
        fs.writeFileSync(
            path.join(itemDir(folder), "editoritems.txt"),
            `${firstLine}"Item"\n{\n\t"Type" "${folder}"\n\t"ItemClass" "ItemBase"\n}\n`,
        )
        if (meta) {
            fs.writeFileSync(
                path.join(itemDir(folder), "meta.json"),
                JSON.stringify(meta),
            )
        }
    }

    test("is noted when its package is imported, from its editoritems' first line", () => {
        // A .bee_pack BeePEE exported (with its meta.json, from an older save)
        importedItem(
            "made",
            "//Generated by BeePEE v1.2.0-beta.1 (@https://github.com/BeemodTools/BeePEE )\n",
            { created: "2026-01-01T00:00:00.000Z", lastSavedVersion: "1.1.0" },
        )
        // By a BeePEE before the first line had the version
        importedItem(
            "old",
            "//Generated by BeePEE (@https://github.com/Areng14/BeePEE )\n",
        )
        // Made by hand
        importedItem("hand", "")
        // Made by hand, with a meta.json that says otherwise
        importedItem("copied", "// Copied from a BeePEE item\n", {
            madeWithBeePEE: true,
        })

        const { processVdfFiles } = require("../packageManager")
        processVdfFiles(dir)

        expect(metaOf("made")).toEqual({
            created: "2026-01-01T00:00:00.000Z",
            madeWithBeePEE: true,
            lastSavedVersion: "1.2.0-beta.1",
        })
        expect(metaOf("old")).toEqual({ madeWithBeePEE: true })
        expect(fs.existsSync(path.join(itemDir("hand"), "meta.json"))).toBe(false)
        expect(metaOf("copied")).toEqual({ madeWithBeePEE: false })
        // Converted as before
        expect(
            JSON.parse(
                fs.readFileSync(path.join(itemDir("made"), "editoritems.json"), "utf8"),
            ).Item.Type,
        ).toBe("made")
    })

    test("is noted with this version when it's saved", async () => {
        fs.mkdirSync(itemDir("vase"), { recursive: true })
        fs.writeFileSync(
            path.join(itemDir("vase"), "editoritems.json"),
            JSON.stringify({
                Item: {
                    Type: "bpee_vase_03AF",
                    Editor: { SubType: { Name: "Vase", Palette: { Tooltip: "VASE" } } },
                    Exporting: { Instances: {} },
                },
            }),
        )
        fs.writeFileSync(
            path.join(itemDir("vase"), "properties.json"),
            JSON.stringify({ Properties: {} }),
        )
        fs.writeFileSync(
            path.join(itemDir("vase"), "meta.json"),
            JSON.stringify({ madeWithBeePEE: true, lastSavedVersion: "1.1.0" }),
        )

        const { saveItem } = require("../saveItem")
        await saveItem({
            id: "bpee_vase_03AF",
            name: "Vase",
            fullItemPath: itemDir("vase"),
            details: {},
        })

        expect(metaOf("vase")).toMatchObject({
            madeWithBeePEE: true,
            lastSavedVersion: APP_VERSION,
        })
    })
})
